#define MONTYPES        35

int Monster_KnownMons[MONTYPES] =
{
    "Dakka_Zombiedude",
    "Dakka_Shotgundude",
    "Dakka_Chaingundude",
    "Dakka_Impdude",
    "Dakka_Demondude",
    "Dakka_Shydude",
    "Dakka_Cacodude",
    "Dakka_Souldude",
    "Dakka_Paindude",
    "Dakka_Dumbdude",
    "Dakka_Spiderdude",
    "Dakka_Fatdude",
    "Dakka_Knightdude",
    "Dakka_Nobledude",
    "Dakka_Skinnydude",
    "Dakka_Cyberdude",
    "Dakka_Smartdude",
    "Dakka_Commiedude",
    "Dakka_Underagedude",

    "Dakka_Heretic_BarfyDude",
    "Dakka_Heretic_ShankDude",
    "Dakka_Heretic_HelmetDude",
    "Dakka_Heretic_SkellyDude",
    "Dakka_Heretic_SpookySkellyDude",
    "Dakka_Heretic_HammerDude",
    "Dakka_Heretic_PunchDude",
    "Dakka_Heretic_GhostpunchDude",
    "Dakka_Heretic_BestNamedDude",
    "Dakka_Heretic_BestNamedGhostDude",
    "Dakka_Heretic_Medudesa",
    "Dakka_Heretic_SnakeWizardDude",
    "Dakka_Heretic_SnakelessWizardDude",
    "Dakka_Heretic_BlasterMaster",
    "Dakka_Heretic_ImpDude",
    "Dakka_Heretic_SuperImpDude",
};

int Monster_Points[MONTYPES] =
{
    20,
    30,
    70,
    60,
    150,
    150,
    400,
    100,
    400,
    300,
    500,
    600,
    500,
    1000,
    700,
    4000,
    3000,
    50,
    100,

    220,
    150,
    700,
    200,
    250,
    3000,
    80,
    100,
    100,
    125,
    280,
    2500,
    7500,
    180,
    40,
    80,
};

